apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: demo-K8s
    image: asepsuhardy14/demo-K8s
    ports:
    - containerPort: 3000
