apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: demo-K8s
        image: asepsuhardy14/demo-K8s
        ports:
        - containerPort: 3000
